# Generated by Django 5.2.12 on 2026-05-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
